version: '3.3'
services:
   php:
        build:
            context: ./php
            dockerfile: Dockerfile
            args:
                - PHP_VERSION=${PHP_VERSION}
        container_name: ${PHP_CONTAINER_NAME}
        restart : always
        volumes:
            - ${PHP_SRC}:/var/www/html/
        ports:
            - ${PHP_PORTS}
        environment:
            - ${MYSQL_HOST}
            - ${MYSQL_DATABASE}
            - ${MYSQL_USER}
            - ${MYSQL_PASSWORD}
        networks:
            - frontend
            - backend
        depends_on:
            - db
  
   db:
        image: mariadb:${MARIADB_VERSION}
        container_name: ${DB_CONTAINER_NAME}
        restart: always
        environment:
            - ${MYSQL_HOST}
            - ${MYSQL_ROOT_PASSWORD}
            - ${MYSQL_DATABASE}
            - ${MYSQL_USER}    
            - ${MYSQL_PASSWORD}
        networks:
            - backend
        command: --default-authentication-plugin=mysql_native_password
   
   phpmyadmin:
        image: phpmyadmin/phpmyadmin:${PMA_VERSION}
        container_name: ${PMA_CONTAINER_NAME}
        restart: always
        depends_on:
            - db
        networks:
            - backend
        environment:
            - ${PMA_HOST}
            - ${PMA_PORT}
        ports:
            - ${PMA_PORTS}
        volumes:
            - /session
networks:
    backend:
    frontend:
